# Generated by Django 3.2.4 on 2021-06-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GSDivinoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GSDivinoApp.fammembers'),
        ),
    ]
