# Generated by Django 3.2.4 on 2021-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSDivinoApp', '0002_wishlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=300)),
                ('price', models.FloatField(max_length=300)),
            ],
        ),
    ]
