# Generated by Django 3.2.4 on 2021-06-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GSDivinoApp', '0003_bill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamMembers',
            new_name='FamMember',
        ),
    ]
