# Generated by Django 3.2.4 on 2021-06-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GSDivinoApp', '0004_rename_fammembers_fammember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Dish',
        ),
    ]
