# Generated by Django 3.2.4 on 2021-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSDivinoApp', '0005_rename_dishes_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='meal',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=300),
        ),
    ]
