# Generated by Django 3.2.4 on 2021-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSDivinoApp', '0006_alter_dish_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircon',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
