# Generated by Django 3.2.4 on 2021-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSDivinoApp', '0007_auto_20210615_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='meal',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=300, null=True),
        ),
    ]
