# Generated by Django 3.2.4 on 2021-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSDivinoApp', '0008_alter_dish_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
